version: '3.8'

services:
  tofu-transcribe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tofu-transcribe
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 